### ISSUE TITLE
Doesn't support Test folder as nightwatch does

### ISSUE THREAD

**Issue by riderx** [TestArmada/magellan-nightwatch-plugin#22]
when i run magellan with some folders in my test folder the pluging don't find them so i can't use the command  
--group=prefix/path  as i was using in nightwatch
there my folders:
**tests:**
**tests/solutions:**
tests/solutions/login.js
tests/solutions/home.js
**tests/demo:**
tests/demo/login.js
tests/demo/home.js

i get : 
```
[INFO] [Nightwatch Plugin] test iterator found nightwatch configuration at: ./conf/nightwatch.json
[INFO] [Nightwatch Plugin] Scanning tests for test files ...
[WARN] [Nightwatch Plugin] Found no test files in tests
```
in my nightwatch.json ->
```
 "src_folders": [
    "./tests"
  ]
```

**Comment by archlichking** [comment]
@riderx currently plugin doesn't search nested folders for the test file. it only search in the folders explicitly in `"src_folders": []`. so for your case you can do

```
"src_folders": [
  "./tests",
  "./tests/solutions",
  "./tests/demo"
 ]
```

**Comment by karthikiyengar** [comment]
+1 - This would be really nice to have.

**Comment by srathibandlarp** [comment]
Any update on this really important feature? seriously it avoids the hassle of writing the 100+ tests file structure in the nightwatch json. Please let us know if the fix is already in.
