### ISSUE TITLE
Nightwatch Screenshot directory: Error: ENOENT - testarmada-magellan-nightwatch-plugin 8.0.8

### ISSUE THREAD

**Issue by barchandune** [TestArmada/magellan-nightwatch-plugin#40]
> Error in creating Nightwatch Screenshot directory: Error: ENOENT: no such file or directory, mkdir
> 
> [INFO] [Nightwatch Plugin] Updating Test Settings with Screenshot Config: {"desiredCapabilities":{"browserName":"chrome"},"nightwatchEnv":"chrome","id":"chrome","executor":"local","screenshots":{"enabled":true,"on_failure":true,"on_error":true,"path":""}}

Seems it's ignoring `test_settings.default.screenshots` which I'm trying to set `enabled: false` here. The issue does not happen if I revert from 8.0.8 to 8.0.3

**Comment by ajoshi0** [comment]
@chiahrens ^^

**Comment by chiahrens** [comment]
reverted code back to 8.0.3 and released 8.0.9
